### ISSUE TITLE
Fullbright issue with setting to enabled

### ISSUE THREAD

**Issue by HowardBaxton** [nPoseTeam/Prim-Params-Editor-plugin#3]
While a user was attempting to set fullbright they found it was not working with this line:
`PRIMEDIT|PRIM_FULLBRIGHT~engines~1~TRUE`

Not sure why but I tried it with a 1 instead of TRUE and it works.
`PRIMEDIT|PRIM_FULLBRIGHT~engines~1~1`

I also tested FALSE which seems to work just fine using FALSE or using 0.

**Comment by LeonaMorro** [comment]
Yes .. that happens because we cast the string "TRUE" to an integer inside the script:
`integer value=(integer)"TRUE"; // value becomes 0`
That happens for all constants defined in LSL, for example "PI, PI_BY_TWO, DEG_TO_RAD, ALL_SIDES ...." they are all casted to 0 or 0.0 or <0.0, 0.0, 0,0> or <0.0, 0.0, 0,0, 0.0>
(BTW: Thats why FALSE, ZERO_VECTOR, ZERO_ROTATION works fine)
I don't see a way around it other than checking for each and every contant like:
```
if(userInput=="TRUE) {
    userInput=(string)TRUE;
}
....
```
Possible solutions:
a) Tell the users not to use constans
b) Implement some "important" constants like "TRUE"
c) Implement "all" constants (I guess this will not work because of memory restrictions)
